spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/server_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  error:
    include-message: always